- hosts: kube_control_plane
  gather_facts: False
  vars_files:
    - ./inventory/gitlab-runner-vars.yml
  tasks:
  - name: add repo
    kubernetes.core.helm_repository:
      name: gitlab
      repo_url: "https://charts.gitlab.io"
  - name: deploy gitlab runner
    kubernetes.core.helm:
      name: gitlab-runner
      chart_ref: gitlab/gitlab-runner
      release_namespace: gitlab-runner
      create_namespace: true
      force: yes
      values:
        gitlabUrl: "{{ gitlabUrl }}"
        runnerRegistrationToken: "{{ runnerRegistrationToken }}"
