---
- name: Include task when RedHat like OS
  include_tasks: yum_package.yml
  when: ansible_os_family == 'RedHat'

- name: Include task when Debian like OS
  include_tasks: apt_package.yml
  when: ansible_os_family == 'Debian'

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Ensure docker is started and enabled on boot.
  service:
    name: docker
    state: started
    enabled: true
